### ISSUE TITLE
Question about input size

### ISSUE THREAD

**Issue by ZdravkoHvarlingov** [hhk7734/tensorflow-yolov4#27]
Hello! Thank you for the amazing work, the package is quite easy to use!

I have a question about the input size - is it intentionally not permitted to specify the input size hence it is fixed to 608x608? This can be easily changed inside the constructor of YOLOv4 class and it is working properly. Unfortunately that directly changes the implementation and makes the PIP package not usable. :(

Thanks in advance for the answer!

**Comment by hhk7734** [comment]
https://github.com/hhk7734/tensorflow-yolov4/blob/0e73c11ebdfc22f6776b49f6d4dd53415592b585/py_src/yolov4/common/base_class.py#L108-L122

`input_size` can be changed as shown below.

```python
from yolov4.tf import YOLOv4

yolo = YOLOv4()

yolo.classes = "coco.names"
yolo.input_size = 416
```
