### ISSUE TITLE
Transfer learning from COCO with different classes

### ISSUE THREAD

**Issue by raz-SX** [hhk7734/tensorflow-yolov4#28]
Hi @hhk7734 thank you for your amazing work!

I'm trying to load the yolov4-tiny-relu.weights into a model with three classes.
When I'm doing so, I'm getting a ValueError("Model and weights file do not match.") from the load_weights function.

To my understanding, the number of classes affects the PANet and the YoloHead, but on the weights.py file the distinction between the two in the way the weights are loaded are the layers' indexes. 

Could you orient me on how to accommodate loading and saving weights for different class numbers? 

Thanks
Raz

**Comment by hhk7734** [comment]
As you said, the number of classes affects some layers. It changes the size of the feature map.
A TF model has info of layers or sub-model. A layer has a unique index or name. So, we can find a layer using an index or name even if the number of classes is changed.

For example, Convolution 17 is in PANetTiny. The name is yolo_conv2d_17, and The filter is 3 * (num_classes + 5).

https://github.com/hhk7734/tensorflow-yolov4/blob/0e73c11ebdfc22f6776b49f6d4dd53415592b585/py_src/yolov4/model/neck.py#L321-L326

The model structure is shown below.

- YoloTiny
  - CSPDarknet53Tiny
    - ...
  - PANetTiny
     - ...
     - yolo_conv2d_17
     - ...
  - YOLOv3HeadTiny
     - ...

weights.py can find layer info using layer name or index.

In `yolo_conv2d_load_weights`,

https://github.com/hhk7734/tensorflow-yolov4/blob/0e73c11ebdfc22f6776b49f6d4dd53415592b585/py_src/yolov4/tf/weights.py#L62
https://github.com/hhk7734/tensorflow-yolov4/blob/0e73c11ebdfc22f6776b49f6d4dd53415592b585/py_src/yolov4/tf/weights.py#L84-L87

---

I don't know if there is a way to extract only the desired classes from the interacting CNN.

**Comment by raz-SX** [comment]
Thanks!
