### ISSUE TITLE
Unable to train on Custom Dataset

### ISSUE THREAD

**Issue by Adeel-Intizar** [hhk7734/tensorflow-yolov4#31]
![error](https://user-images.githubusercontent.com/56041154/96347234-afd68d80-10b9-11eb-9643-5f8c326ba2a3.PNG)
I wanted to train it on my custom dataset, but it is consistently raising an error
"IndexError: index 224 is out of bounds for axis 1 with size 20"
and this error is changing values but it is consistent

Any Help would be appreciated. 
Thanks

**Comment by hhk7734** [comment]
Too little information.
Can you share your script? and dataset files

why are `validation_steps` and `steps_per_epoch` zero?

**Comment by hhk7734** [comment]
commit: fcea285ffa05845b6cd59e188921eff6f02186cb

If you use a converted-coco dataset, the data format is shown below.

```text
000000000139.jpg 58,0.389578,0.416103,0.038594,0.163146 62,0.127641,0.505153,0.233312,0.222700 62,0.934195,0.583462,0.127109,0.184812 56,0.604656,0.632547,0.087500,0.241385 56,0.502508,0.627324,0.096609,0.231174 56,0.669195,0.618991,0.047141,0.190986 56,0.512797,0.528251,0.033719,0.027207 0,0.686445,0.531960,0.082891,0.323967 0,0.612484,0.446197,0.023625,0.083897 68,0.811859,0.501725,0.023031,0.037488 72,0.786320,0.536373,0.031703,0.254249 73,0.956156,0.771702,0.022406,0.107300 73,0.968250,0.778075,0.020125,0.109014 74,0.710555,0.310000,0.021828,0.051362 75,0.886562,0.831608,0.057313,0.210493 75,0.556945,0.516702,0.017766,0.052934 56,0.651664,0.528826,0.015047,0.029390 75,0.388047,0.478415,0.022219,0.041385 75,0.533836,0.487946,0.015203,0.039272 60,0.599984,0.647148,0.196188,0.208756
000000000285.jpg 21,0.501220,0.548094,0.997560,0.881156
000000000632.jpg 59,0.318570,0.768064,0.626922,0.431159 58,0.333984,0.378375,0.094969,0.191284 73,0.719164,0.435393,0.013391,0.073685 73,0.714562,0.558872,0.012531,0.070248 73,0.699094,0.657288,0.008313,0.082153 73,0.800039,0.433561,0.018984,0.076149 73,0.767578,0.441729,0.011687,0.058075 56,0.464344,0.567899,0.163625,0.181553 58,0.607195,0.587723,0.128922,0.296066 73,0.743086,0.434141,0.045828,0.074617 73,0.842531,0.556491,0.038125,0.083706 73,0.814734,0.435870,0.006375,0.070787 73,0.780359,0.143085,0.006375,0.056646 73,0.821438,0.240714,0.004375,0.078199 73,0.796336,0.328986,0.050922,0.013168 73,0.748336,0.520373,0.075859,0.025135 73,0.727953,0.559700,0.012875,0.068965 73,0.769531,0.402692,0.239063,0.627329
...
```

- `class_id` is an integer greater than or equal to 0.
- `center_x`, `center_y`, `width`and `height` are between 0.0 and 1.0.

**Comment by Adeel-Intizar** [comment]
Thank you for your reply, I have attached the files “script.txt” contains my script which I used in google colab, and “train.txt and val.txt” contains dataset info

**Comment by hhk7734** [comment]
You should modify train.txt and val.txt.
`center_x`, `center_y`, `width` and `height` are between 0.0 and 1.0.

For example, 
Suppose the image width and height are 600 and 500
`image_0001.jpg 0,49,30,349,137` -> `image_0001.jpg 0,49/600,30/500,349/600,137/500`
-> `image_0001.jpg 0,0.0817,0.06,0.58167,0.274`

**Comment by Adeel-Intizar** [comment]
Thank you for your help..

**Comment by wmcnally** [comment]
@hhk7734 @Adeel-Intizar Just to confirm, should the xy positions in the dataset .txt file refer to the center of the bounding box or the top left corner of the bounding box? Thanks.

**Comment by wmcnally** [comment]
Nevermind, I confirmed that the xy positions in the dataset .txt file refer to the center of the bounding box.
