### ISSUE TITLE
Cannot add config file for newly trained custom weight file

### ISSUE THREAD

**Issue by tyseng92** [hhk7734/tensorflow-yolov4#32]
I was trying to train a new custom detector by adding one additional new class object into the reduced COCO dataset (1 new class + 35 classes). And I have trained new weight file using yolov4.conv.137 with modified yolov4-custom.cfg from [Darknet AlexeyAB](https://github.com/AlexeyAB/darknet). Is there any way to add my yolov4-custom.cfg into your code so that the detector could identify the new object? Thanks.

**Comment by tyseng92** [comment]
.names, .cfg, .weight files are all in this [link](https://drive.google.com/drive/folders/1GcToZOY9xXxZqajMWuIKMigo66huauAE?usp=sharing).

**Comment by hhk7734** [comment]
If you haven't done anything other than modifying the number of classes,

```python
from yolov4.tf import YOLOv4

yolo = YOLOv4()

yolo.classes = r"c:/Users/win/Downloads/coco17.names"

yolo.make_model()
yolo.load_weights(r"c:/Users/win/Downloads/yolov4-custom_36cls_70000.weights", weights_type="yolo")

yolo.inference(0, is_image=False)
```

I tested the above script with cam.

**Comment by tyseng92** [comment]
Thanks for the testing. I have tested the name and weight files on my code which is similar to your, but it seems cannot detected the new class called 'lozenges'. [Here](https://cdn-prd-02.pnp.co.za/sys-master/images/hf9/ha3/9221989433374/silo-50836376-front-287098_400Wx400H) is the sample image of the lozenges. Just wonder if the problem comes from the absence of the yolov4-custom.cfg config file. Note that the class number is 36 and the filter size is 123. Should I set the `yolo.input_size = 416 yolo.batch_size = 64` as well to match the config file? Thanks.

**Comment by hhk7734** [comment]
![result](https://user-images.githubusercontent.com/21096989/96671783-a1c88b80-139d-11eb-9995-ed1cb6c011d5.png)

```python
from yolov4.tf import YOLOv4

yolo = YOLOv4()

yolo.classes = r"c:/Users/win/Downloads/coco17.names"

yolo.make_model()
yolo.load_weights(r"c:/Users/win/Downloads/yolov4-custom_36cls_70000.weights", weights_type="yolo")

yolo.inference(media_path=r"c:/Users/win/Downloads/silo-50836376-front-287098_400Wx400H.jfif")
```

:)

**Comment by tyseng92** [comment]
I have solved my problem on my side too. Thanks for your verification.
