### ISSUE TITLE
support for data augmentation?

### ISSUE THREAD

**Issue by lidorshimoni** [hhk7734/tensorflow-yolov4#33]
is it possible to do any sort of data augmentation for training with this library? 
if it's not possible yet, when will it be?
thanks

**Comment by hhk7734** [comment]
https://github.com/hhk7734/tensorflow-yolov4/blob/fcea285ffa05845b6cd59e188921eff6f02186cb/py_src/yolov4/tf/dataset.py#L325
https://github.com/hhk7734/tensorflow-yolov4/blob/fcea285ffa05845b6cd59e188921eff6f02186cb/py_src/yolov4/tf/dataset.py#L356
https://github.com/hhk7734/tensorflow-yolov4/blob/fcea285ffa05845b6cd59e188921eff6f02186cb/py_src/yolov4/tf/dataset.py#L363
https://github.com/hhk7734/tensorflow-yolov4/blob/fcea285ffa05845b6cd59e188921eff6f02186cb/py_src/yolov4/tf/dataset.py#L269-L281

There is not yet an option to select data augmentation. If you want to change it, you have to change the above part yourself.
