### ISSUE TITLE
What is the purpose of Dataset.grid in py_src/yolov4/tf/dataset.py

### ISSUE THREAD

**Issue by daniel-SX** [hhk7734/tensorflow-yolov4#44]
In the Dataset object you defined a grid attribute which is only used in line 182:
https://github.com/hhk7734/tensorflow-yolov4/blob/fd45eea11d2de86664978184e6b798daf2546cdc/py_src/yolov4/tf/dataset.py#L182-L183

I don't understand the purpose of this assignment , because later the xywh gt vector is assigned to each grid point in line 222:
https://github.com/hhk7734/tensorflow-yolov4/blob/fd45eea11d2de86664978184e6b798daf2546cdc/py_src/yolov4/tf/dataset.py#L222

And when calculating the xiou_loss only these xywh gt vectors are used. So there seems to be no use anywhere for the _grid values.

**Comment by hhk7734** [comment]
The grid's x and y values ​​are pre-assigned in case they are used in calculations.
If it is unnecessary and has an impact on the training time, I think we can erase it after testing. :)
