### ISSUE TITLE
what about data augmentation?

### ISSUE THREAD

**Issue by Adeel-Intizar** [hhk7734/tensorflow-yolov4#46]
Does this implementation use data augmentation, i actually wanna make it more accurate, i wonder if data augmentation can be used in this implementation to generate much more accurate results?

**Comment by hhk7734** [comment]
https://github.com/hhk7734/tensorflow-yolov4/blob/fd45eea11d2de86664978184e6b798daf2546cdc/py_src/yolov4/tf/__init__.py#L217-L237

https://github.com/hhk7734/tensorflow-yolov4/blob/fd45eea11d2de86664978184e6b798daf2546cdc/py_src/yolov4/tf/dataset.py#L311-L312

https://github.com/hhk7734/tensorflow-yolov4/blob/fd45eea11d2de86664978184e6b798daf2546cdc/py_src/yolov4/tf/dataset.py#L282-L294


If you want to use other augmentation, add to _next_random_augmentation_data().

**Comment by Adeel-Intizar** [comment]
Thank you! :)
