### ISSUE TITLE
when using tensorflow not tflite runtime the load delegate method is not found to use coral

### ISSUE THREAD

**Issue by fogelton** [hhk7734/tensorflow-yolov4#48]
in tflite/__init__
bool variable can be added

```python
tflitePresent=True
try:
    import tflite_runtime.interpreter as tflite
except ModuleNotFoundError:
    tflitePresent=False
    import tensorflow.lite as tflite
```

and later

```python
        if tflitePresent:
            self.interpreter = tflite.Interpreter(
                model_path=tflite_path,
                experimental_delegates=[
                    tflite.load_delegate("libedgetpu.so.1")
                ],
            )
        else:
            self.interpreter = tflite.Interpreter(
                model_path=tflite_path,
                experimental_delegates=[
                    tflite.experimental.load_delegate("libedgetpu.so.1")
                ],
            )
```

to prevent the error, but maybe there is more elegant way :)

**Comment by hhk7734** [comment]
On coral dev board?

**Comment by fogelton** [comment]
pc + usb coral

**Comment by hhk7734** [comment]
```python
try:
    import tflite_runtime.interpreter as tflite
    from tflite_runtime.interpreter import load_delegate
except ModuleNotFoundError:
    import tensorflow.lite as tflite
    from tensorflow.lite.experimental import load_delegate
```

```python
        if self.tpu:
            self.interpreter = tflite.Interpreter(
                model_path=tflite_path,
                experimental_delegates=[load_delegate("libedgetpu.so.1")],
            )
        else:
            self.interpreter = tflite.Interpreter(model_path=tflite_path)
```

How about this?
If you can test, please test and make pull request :)

**Comment by fogelton** [comment]
I just updated the package to the latest version and I get an import error for the load_delegate
I do not know why..  i have tensorflow2.4 python3.8 when I execute python3 and only the given commands, the results:

>>> import tensorflow.lite as tflite
2021-01-05 16:27:54.947757: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-01-05 16:27:54.947782: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
>>> from tensorflow.lite.experimental import load_delegate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'load_delegate' from 'tensorflow.lite.experimental'

when I execute the commands in python with tflite_runtime installed

import tflite_runtime.interpreter as tflite
from tflite_runtime.interpreter import load_delegate

the load_delegate is imported successfully, this is very weird and above my knowledge

**Comment by hhk7734** [comment]
I'm sorry.
There seemed to be no problem, so I committed without testing. :(

Could you test the code below?
```python
try:
    import tflite_runtime.interpreter as tflite
    from tflite_runtime.interpreter import load_delegate
except ModuleNotFoundError:
    import tensorflow.lite as tflite

    load_delegate = tflite.experimental.load_delegate
```

**Comment by fogelton** [comment]
it works, thanks
