### ISSUE TITLE
Installation error in Windows

### ISSUE THREAD

**Issue by Twinkle126** [hhk7734/tensorflow-yolov4#5]
Hi,

When I run command `python -m pip install yolov4` in my virtual env, I am getting below error-
![installation_error_windows](https://user-images.githubusercontent.com/36033503/85969795-4df8f780-b9e6-11ea-9fab-11144c75ae6a.JPG)

My system setup is as below-
Python 3.6.10
Windows 10
Cuda 10.1
cuDNN 7.6.0

**Comment by hhk7734** [comment]
@Twinkle126

I tested it on Linux only. :sweat_smile:
I'll test it after a while

**Comment by hhk7734** [comment]
Did you install TensorFlow 2?

**Comment by Twinkle126** [comment]
Yes, I installed TF2.

**Comment by hhk7734** [comment]
Hmm...
I tested yolov4 and it was successfull.

- Install python3.7.8
- Set environment path
  - C:\Program Files\Python37
  - C:\Users\hhk7734\AppData\Roaming\Python\Python37\Scripts

```shell
python -m pip install -U setuptools pip
```

```shell
python -m pip install tensorflow opencv-python ipython
```

```shell
python -m pip install yolov4
```

```shell
ipython

In [1]: from yolov4.tf import YOLOv4
   ...:
   ...: yolo = YOLOv4()
   ...:
   ...: yolo.classes = "C:/Users/hhk7734/Desktop/yolov4/data/classes/coco.names"
   ...:
   ...: yolo.make_model()
   ...: yolo.load_weights("C:/Users/hhk7734/Desktop/yolov4.weights", weights_type="yolo")
   ...:
   ...: yolo.inference(
   ...:     media_path="C:/Users/hhk7734/Desktop/yolov4/data/kite.jpg",
   ...: )
```

**Comment by Twinkle126** [comment]
It seems issue with Python 3.6.10. I will upgrade it to 3.7 and then use it.
Thanks for looking into this and your prompt reply.
