### ISSUE TITLE
Can I use datasets in Yolo format for training?

### ISSUE THREAD

**Issue by x12901** [hhk7734/tensorflow-yolov4#59]
Great project. I use lableimg for labeling. But the project does not seem to support labels exported by this tool.Whether to support it in the future?

**Comment by hhk7734** [comment]
labelImg supports yolo format dataset.

https://wiki.loliot.net/docs/lang/python/libraries/yolov4/python-yolov4-dataset#yolo

```python
dataset = yolo.load_dataset("image_path.txt", image_path_prefix="/<prefix>", dataset_type="yolo")
```

**Comment by hhk7734** [comment]
Did you use another format?

**Comment by x12901** [comment]
Thank you.
