### ISSUE TITLE
ValueError: Model and weights file do not match.

### ISSUE THREAD

**Issue by Twinkle126** [hhk7734/tensorflow-yolov4#7]
Hi,

I have trained a custom dataset with YOLOv4.
Now I am trying to use the trained model on test image but I am getting following error-
![tf2error](https://user-images.githubusercontent.com/36033503/86379430-7879d780-bca8-11ea-8162-50649b825520.JPG)

My env is as below-
Python 3.7.6
TensorFlow 2.0.0
Windows 10

Please suggest.

**Comment by hhk7734** [comment]
Can you share convert.py?

**Comment by Twinkle126** [comment]
This is my file-
[convert.txt](https://github.com/hhk7734/tensorflow-yolov4/files/4867629/convert.txt)

**Comment by hhk7734** [comment]
It seems that the numbers of classes in `yolo-obj_best.weights` and in `obj.names` do not match.

**Comment by Twinkle126** [comment]
But I have tested the new images with Darknet command using same weights file and it works well.

**Comment by hhk7734** [comment]
Can you share `xx.cfg` used to train? and `obj.names`.

**Comment by Twinkle126** [comment]
[yolo-obj.txt](https://github.com/hhk7734/tensorflow-yolov4/files/4869395/yolo-obj.txt)

[obj_names.txt](https://github.com/hhk7734/tensorflow-yolov4/files/4869396/obj_names.txt)

**Comment by hhk7734** [comment]
hmm.. It seems no problem. I don't know why.

To create the same problem,
I trained pothole(1 class) images using darknet yolov4. `hole.weights` file size is 256.0 MB (256,015,980 bytes). It runs successfully
