### ISSUE TITLE
Is scaled-YOLOv4 going to be supported?

### ISSUE THREAD

**Issue by 4ku** [hhk7734/tensorflow-yolov4#74]

**Comment by hhk7734** [comment]
Supports **yolov4-csp** and **yolov4x-mish** without training part.

Some cfg options are not yet supported(almost training part options). So, download the config file in this repo.
https://github.com/hhk7734/tensorflow-yolov4/tree/master/config

```python
from yolov4.tf import YOLOv4, save_as_tflite

yolo = YOLOv4()

yolo.config.parse_names("coco.names")
yolo.config.parse_cfg("yolov4-csp.cfg")

yolo.make_model()
yolo.load_weights("yolov4-csp.weights", weights_type="yolo")
yolo.summary(summary_type="yolo")
yolo.summary()

yolo.inference(media_path="kite.jpg")

yolo.inference(media_path="road.mp4", is_image=False)

yolo.inference(
    "/dev/video0",
    is_image=False,
    cv_apiPreference=cv2.CAP_V4L2,
    cv_frame_size=(640, 480),
    cv_fourcc="YUYV",
)
```

**Comment by 4ku** [comment]
@hhk7734 Thank you) And what about scaled tiny model?

**Comment by hhk7734** [comment]
Did you mean `config/yolov4-tiny-relu-new_coords.cfg`?
I'm testing it because I thought it might show a bit faster speed on the EdgeTpu.
I'm busy these days, so I paused for a while.

**Comment by 4ku** [comment]
I mean [this](https://github.com/WongKinYiu/ScaledYOLOv4/tree/yolov4-tiny). But I don't know, may be it's the same.

**Comment by hhk7734** [comment]
It seems to be just yolov4 tiny.

**Comment by 4ku** [comment]
May be, but configs differs a little

**Comment by hhk7734** [comment]
The options that differ are probably training-related options.

**Comment by 4ku** [comment]
ok, thank you
