### ISSUE TITLE
How to get the coordinates of the bounding box in YOLOv4?

### ISSUE THREAD

**Issue by Markmichelin** [hhk7734/tensorflow-yolov4#77]
Sorry i want to know How to get the coordinates of the bounding box in YOLOv4? thanks

**Comment by hhk7734** [comment]
https://github.com/hhk7734/tensorflow-yolov4/blob/3d31292cefba198b1528a90b3f435204efe7be73/py_src/yolov4/tf/__init__.py#L105-L131

https://github.com/hhk7734/tensorflow-yolov4/blob/3d31292cefba198b1528a90b3f435204efe7be73/py_src/yolov4/common/base_class.py#L152-L156

Put an image in `predict()`. Then, you can get the bbox.

**Comment by Markmichelin** [comment]
Sorry i want to run in v2.1.0 what can i do ?

**Comment by hhk7734** [comment]
https://wiki.loliot.net/docs/lang/python/libraries/yolov4/python-yolov4-about#tensorflow

```python
from yolov4.tf import YOLOv4

yolo = YOLOv4()
# yolo = YOLOv4(tiny=True)

yolo.classes = "coco.names"
yolo.input_size = (640, 480)

yolo.make_model()
yolo.load_weights("yolov4.weights", weights_type="yolo")
# yolo.load_weights("yolov4-tiny.weights", weights_type="yolo")

frame = cv2.imread(media_path) 
frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB) 

bboxes = self.predict(frame_rgb) 
```
