### ISSUE TITLE
How to use GPU for Inferencing?

### ISSUE THREAD

**Issue by JayantGoel001** [hhk7734/tensorflow-yolov4#79]
Hey @hhk7734 
Can we GPU's for inferencing the yolov4 model?

**Comment by hhk7734** [comment]
I tested on Titan RTX and Tesla V100(colab).

**Comment by JayantGoel001** [comment]
> I tested on Titan RTX and Tesla V100(colab).

So I don't need to do any extra to use GPU?

**Comment by hhk7734** [comment]
Whether or not to use a GPU has little to do with this library.
Most of them are TensorFlow settings, and in general, TF will automatically assign the model to the GPU.

**Comment by hhk7734** [comment]
https://github.com/hhk7734/tensorflow-yolov4/blob/3d31292cefba198b1528a90b3f435204efe7be73/py_src/yolov4/tf/__init__.py#L45-L48

Maybe, only this part is related to GPU settings.

**Comment by JayantGoel001** [comment]
Ok 
Yup Got It
Thanks  😁
